import { EmailType } from '../types/Type.ts';

const tempData: Array<EmailType> = [// User 1: Alice
  {
    emailId: '1',
    from: { name: 'Alice', email: 'alice@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Lunch Meeting Proposal',
    time: '2023-10-04T23:05:00Z',
    message: 'Hello Tanzeel, I hope you\'re doing well. I wanted to propose a lunch meeting to discuss the upcoming project. Let me know your availability for next week. Looking forward to your response. Best regards, Alice.',
  }, {
    emailId: '2',
    from: { name: 'Alice', email: 'alice@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Project Deadline Reminder',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, just a quick reminder that the project deadline is approaching. Please ensure all tasks are completed and submitted by the end of this week. Let me know if you need any assistance. Best, Alice.',
  }, {
    emailId: '3',
    from: { name: 'Alice', email: 'alice@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Report Submission',
    time: '2023-10-04T23:05:00Z',
    message: 'Dear Tanzeel, I have attached the report you requested. Please review it and let me know if there are any changes needed. Looking forward to your feedback. Best regards, Alice.',
  }, {
    emailId: '4',
    from: { name: 'Alice', email: 'alice@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Document Review Request',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, I have shared a document for your review. Please take a look and provide your feedback by the end of the week. Let me know if you have any questions. Best, Alice.',
  }, {
    emailId: '5',
    from: { name: 'Alice', email: 'alice@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Meeting Schedule',
    time: '2023-10-04T23:05:00Z',
    message: 'Hello Tanzeel, let\'s schedule a meeting for next week to discuss the project progress. Please let me know your availability. Looking forward to your response. Best regards, Alice.',
  },

  // User 2: Bob
  {
    emailId: '6',
    from: { name: 'Bob', email: 'bob@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Project Update',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, here\'s the latest update on the project. Everything is on track, and we are meeting our milestones. Let me know if you have any questions. Best, Bob.',
  }, {
    emailId: '7',
    from: { name: 'Bob', email: 'bob@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'File Attachment',
    time: '2023-10-04T23:05:00Z',
    message: 'Dear Tanzeel, please check the attached file for the details. Let me know if you need any further information. Looking forward to your feedback. Best regards, Bob.',
  }, {
    emailId: '8',
    from: { name: 'Bob', email: 'bob@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Thoughts on Proposal',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, I wanted to get your thoughts on the proposal I shared. Let me know if you have any suggestions or concerns. Best, Bob.',
  }, {
    emailId: '9',
    from: { name: 'Bob', email: 'bob@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Budget Finalization',
    time: '2023-10-04T23:05:00Z',
    message: 'Hello Tanzeel, we need to finalize the budget for the project. Please review the details and let me know your approval. Best regards, Bob.',
  }, {
    emailId: '10',
    from: { name: 'Bob', email: 'bob@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Thank You',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, thanks for your help with the project. Your support has been invaluable. Let me know if you need anything from my side. Best, Bob.',
  },

  // User 3: Charlie
  {
    emailId: '11',
    from: { name: 'Charlie', email: 'charlie@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Project Plan',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, here\'s the plan for the upcoming project. Please review it and let me know your thoughts. Looking forward to your feedback. Best, Charlie.',
  }, {
    emailId: '12',
    from: { name: 'Charlie', email: 'charlie@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Proposal Review',
    time: '2023-10-04T23:05:00Z',
    message: 'Dear Tanzeel, I have shared a proposal for your review. Please take a look and let me know if you have any suggestions. Best regards, Charlie.',
  }, {
    emailId: '13',
    from: { name: 'Charlie', email: 'charlie@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Discussion Tomorrow',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, let\'s discuss the project details tomorrow. Please let me know your availability. Looking forward to our conversation. Best, Charlie.',
  }, {
    emailId: '14',
    from: { name: 'Charlie', email: 'charlie@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Updated Schedule',
    time: '2023-10-04T23:05:00Z',
    message: 'Hello Tanzeel, here\'s the updated schedule for the project. Please review it and let me know if there are any conflicts. Best regards, Charlie.',
  }, {
    emailId: '15',
    from: { name: 'Charlie', email: 'charlie@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Feedback Appreciated',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, thanks for your feedback on the project. It has been very helpful. Let me know if you need anything else. Best, Charlie.',
  },

  // User 4: David
  {
    emailId: '16',
    from: { name: 'David', email: 'david@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Report Submission',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, I have attached the report for your review. Please take a look and let me know if there are any changes needed. Best regards, David.',
  }, {
    emailId: '17',
    from: { name: 'David', email: 'david@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Details Check',
    time: '2023-10-04T23:05:00Z',
    message: 'Dear Tanzeel, please check the details in the attached file. Let me know if you need any further information. Best, David.',
  }, {
    emailId: '18',
    from: { name: 'David', email: 'david@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Plan Finalization',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, let\'s finalize the plan for the project. Please review the details and let me know your approval. Best regards, David.',
  }, {
    emailId: '19',
    from: { name: 'David', email: 'david@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Updated Budget',
    time: '2023-10-04T23:05:00Z',
    message: 'Hello Tanzeel, here\'s the updated budget for the project. Please review it and let me know if there are any issues. Best, David.',
  }, {
    emailId: '20',
    from: { name: 'David', email: 'david@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Thank You',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, thanks for your support on the project. Your help has been invaluable. Let me know if you need anything from my side. Best, David.',
  },

  // User 5: Eve
  {
    emailId: '21',
    from: { name: 'Eve', email: 'eve@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Project Update',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, here\'s the latest update on the project. Everything is progressing as planned. Let me know if you have any questions. Best, Eve.',
  }, {
    emailId: '22',
    from: { name: 'Eve', email: 'eve@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Document Review',
    time: '2023-10-04T23:05:00Z',
    message: 'Dear Tanzeel, please review the document I shared. Let me know if you have any feedback or suggestions. Best regards, Eve.',
  }, {
    emailId: '23',
    from: { name: 'Eve', email: 'eve@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Discussion Tomorrow',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, let\'s discuss the project details tomorrow. Please let me know your availability. Looking forward to our conversation. Best, Eve.',
  }, {
    emailId: '24',
    from: { name: 'Eve', email: 'eve@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Updated Schedule',
    time: '2023-10-04T23:05:00Z',
    message: 'Hello Tanzeel, here\'s the updated schedule for the project. Please review it and let me know if there are any conflicts. Best regards, Eve.',
  }, {
    emailId: '25',
    from: { name: 'Eve', email: 'eve@example.com' },
    to: { name: 'Tanzeel', email: 'tanzeel@gmail.com' },
    isRead: false,
    title: 'Thank You',
    time: '2023-10-04T23:05:00Z',
    message: 'Hi Tanzeel, thanks for your help with the project. Your support has been invaluable. Let me know if you need anything from my side. Best, Eve.',
  }];

export default tempData;